In [65]:
import sqlite3
import numpy as np
import pandas as pd
import keras
import math
import datetime
import tensorflowjs as tfjs
import pickle
import datetime
import calendar
import sklearn.metrics as metrics
from keras.models import Sequential, model_from_yaml, load_model
from keras.layers import Dense, LSTM, Dropout, Embedding, Masking
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.base import BaseEstimator, TransformerMixin
from imblearn.over_sampling import SMOTE

In [43]:
def encodeOutputVariable(y):
    labelencoder_Y_Origin = LabelEncoder()
    y = labelencoder_Y_Origin.fit_transform(y.astype(str))
    return y

def encodeCategoricalData(X, index):
    # encode categorical data
    labelencoder_X_Origin = LabelEncoder()
    X[:, index] = labelencoder_X_Origin.fit_transform(X[:, index].astype(str))
    return X    

def manualEncodeLongStrings(X, column):
    index = 0
    test = 0
    keys = {}
    for row in X:
        key = row[column].replace(", ", "").replace(" ", "")
        if (keys.get(key) == None):
            keys[key] = index
            index += 1
        X[test][column] = keys.get(key)
        test += 1
    return X
    
def defaultMinimumValues(values): 
    for index, x in enumerate(values):
        x = [float(y) if y != None and float(y) > 0.0 else 0 for y in x]
        values[index] = x
    return pd.DataFrame(values)

def encodeHotEncoder(X, categoryIndex):
    # meant to create dummy variables for each category data
    # you only use it for one column at a time, output will be the number of columns
    # needed to represent all discrete values of column
    onehotencoder = OneHotEncoder(categorical_features = [categoryIndex])
    X = defaultMinimumValues(X)
    X = onehotencoder.fit_transform(X.astype(str)).toarray()    
    X = X[:, 1:]
    return X

def determineTotalTime(startDay, startTime, endDay, endTime):
    minsPerDay = 24 * 60
    totalStart = (int(startDay) * minsPerDay) + int(startTime)
    totalEnd = (int(endDay) * minsPerDay) + int(endTime)
    return totalEnd - totalStart

def saveModelThroughPickle(model, filename):
    pickle.dump(model, open(filename, "wb"))

def outputPredictorResults(y_test, y_pred, title):
    # output results for model predictions
    print("For", title, "Classification")
    print(metrics.accuracy_score(y_test, y_pred) * 100)
    print(metrics.confusion_matrix(y_test, y_pred))
    print(pd.crosstab(y_test.ravel(), y_pred.ravel(), rownames=["True"], colnames=["Predicted"], margins=True))
    print(metrics.classification_report(y_test, y_pred))
    print(metrics.zero_one_loss(y_test, y_pred))
#     print(metrics.log_loss(y_test, y_pred))
#    print(metrics.roc_auc_score(y_test, y_pred))    

In [ ]:
class MinimumData(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        
    def fit(self, X, y):
        

In [54]:
def createArtificialNeuralNetwork(X_train, y_train, X_test, y_test):
    # create ANN
    print("\nArtificial Neural Network Classifier Section")
    print("---------------------------------")

    # initialize the ann
    classifier = Sequential()

    # adding the input layer and the first hidden layer
    classifier.add(Dense(100, kernel_initializer = "uniform", activation = "relu", input_dim = 41))
    
    classifier.add(Dense(90, kernel_initializer = "uniform", activation="relu"))
    
    classifier.add(Dense(75, kernel_initializer = "uniform", activation="relu"))
    
    # adding the second hidden layer
    classifier.add(Dense(50, kernel_initializer = "uniform", activation = "relu"))

    # adding the third hidden layer
    classifier.add(Dense(25, kernel_initializer = "uniform", activation = "relu"))

    classifier.add(Dense(20, kernel_initializer = "uniform", activation="relu"))
    
    # adding the fourth hidden layer
    classifier.add(Dense(10, kernel_initializer = "uniform", activation = "relu"))
    
    classifier.add(Dense(5, kernel_initializer = "uniform", activation="relu"))

    # adding the output layer 
    classifier.add(Dense(1, kernel_initializer = "uniform", activation = "sigmoid"))

    # compiling the ANN
    classifier.compile(optimizer = "adam", loss = "mean_squared_error", metrics = ["accuracy"])

    # fitting the ANN to the training set
    classifier.fit(X_train, y_train, batch_size = 100, epochs = 200) 
    
    y_pred = classifier.predict(X_test)
    y_pred = (y_pred > 0.5)
    
    # output results
    outputPredictorResults(y_test, y_pred, "Artificial Neural Network")
    
    classifier.save("ann_cause_model.h5")
    classifier.save("ann_cause_model_weights.h5")
    
def creatingRandomForestPredictor(X_train, y_train, X_test, y_test):
    print("\nRandom Forest Classifier Section")
    print("---------------------------------")
    
    # initialize the Random Forest Classifier
    random_forest_classifier = RandomForestClassifier(**{'n_jobs': -1,
        'n_estimators': 1500,
        'warm_start': True, 
        'max_features': 0.5,
        'max_depth': 15,
        'min_samples_leaf': 2,
        'max_features' : 'sqrt',
        'random_state' : 0,
        'verbose': 0
                                                      })
    # run through oversampler simplifier
    oversampler = SMOTE(random_state=0)
    smote_X_train, smote_y_train = oversampler.fit_sample(X_train, y_train)
    
    # fitting Random Forest to the training set
    random_forest_classifier.fit(smote_X_train, smote_y_train)
    
    # Predicting the Test set results
    rf_y_pred = random_forest_classifier.predict(X_test)
    
    # use the threshold of error to determine whether a prediction is valid
    rf_y_pred = (rf_y_pred > 0.5)
    
    # making the confusion matrix
    cm = metrics.confusion_matrix(y_test.ravel(), rf_y_pred.ravel())
    
    print("Training set Score: ", random_forest_classifier.score(X_train, y_train))
    print("Testing set Score: ", random_forest_classifier.score(X_test, y_test)) 
    
    outputPredictorResults(y_test, rf_y_pred, "Random Forest")
    saveModelThroughPickle(random_forest_classifier, "random_forest_cause_model.h5")
    
def createNaiveBayesModel(X_train, y_train, X_test, y_test, preprocess):
    # initialize the Naive Bayes Classifier
    classifier = GaussianNB()
    
    # hook up the preprocess step with the classifier params and create the pipeline
    model = make_pipeline(preprocess, classifier)
    
    # fit the Naive Bayes Classifier to the training set
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    y_pred = (y_pred > 0.5)
    
    print("Training set Score: ", model.score(X_train, y_train))
    print("Testing set Score: ", model.score(X_test, y_test))
    
    outputPredictorResults(y_test, y_pred, "Naive Bayes")
    saveModelThroughPickle(classifier, "naive_bayes_cause_model.h5")

In [55]:
sqlite_file = "./wildfires.sqlite"

# connecting to the database file and saving the select
conn = sqlite3.connect(sqlite_file)
dataset = pd.read_sql_query("select * from Fires limit 5000;", conn)

In [56]:
dataset.iloc[:,:]

OBJECTID  FOD_ID      FPA_ID SOURCE_SYSTEM_TYPE SOURCE_SYSTEM  \
0            1       1  FS-1418826                FED   FS-FIRESTAT   
1            2       2  FS-1418827                FED   FS-FIRESTAT   
2            3       3  FS-1418835                FED   FS-FIRESTAT   
3            4       4  FS-1418845                FED   FS-FIRESTAT   
4            5       5  FS-1418847                FED   FS-FIRESTAT   
5            6       6  FS-1418849                FED   FS-FIRESTAT   
6            7       7  FS-1418851                FED   FS-FIRESTAT   
7            8       8  FS-1418854                FED   FS-FIRESTAT   
8            9       9  FS-1418856                FED   FS-FIRESTAT   
9           10      10  FS-1418859                FED   FS-FIRESTAT   
10          11      11  FS-1418861                FED   FS-FIRESTAT   
11          12      12  FS-1418863                FED   FS-FIRESTAT   
12          13      13  FS-1418865                FED   FS-FIRESTAT   
13          14      14  FS-1418872                FED   FS-FIRESTAT   
14          15      15  FS-1418874                FED   FS-FIRESTAT   
15          16      16  FS-1418876                FED   FS-FIRESTAT   
16          17      17  FS-1418878                FED   FS-FIRESTAT   
17          18      18  FS-1418881                FED   FS-FIRESTAT   
18          19      19  FS-1418884                FED   FS-FIRESTAT   
19          20      20  FS-1418887                FED   FS-FIRESTAT   
20          21      21  FS-1418888                FED   FS-FIRESTAT   
21          22      22  FS-1418893                FED   FS-FIRESTAT   
22          23      23  FS-1418894                FED   FS-FIRESTAT   
23          24      24  FS-1418895                FED   FS-FIRESTAT   
24          25      25  FS-1418896                FED   FS-FIRESTAT   
25          26      26  FS-1418897                FED   FS-FIRESTAT   
26          27      27  FS-1418898                FED   FS-FIRESTAT   
27          28      28  FS-1418903                FED   FS-FIRESTAT   
28          29      29  FS-1418904                FED   FS-FIRESTAT   
29          30      30  FS-1418905                FED   FS-FIRESTAT   
...        ...     ...         ...                ...           ...   
4970      4971    4994  FS-1428564                FED   FS-FIRESTAT   
4971      4972    4995  FS-1428565                FED   FS-FIRESTAT   
4972      4973    4996  FS-1428566                FED   FS-FIRESTAT   
4973      4974    4997  FS-1428567                FED   FS-FIRESTAT   
4974      4975    4998  FS-1428575                FED   FS-FIRESTAT   
4975      4976    4999  FS-1428576                FED   FS-FIRESTAT   
4976      4977    5000  FS-1428577                FED   FS-FIRESTAT   
4977      4978    5001  FS-1428580                FED   FS-FIRESTAT   
4978      4979    5002  FS-1428585                FED   FS-FIRESTAT   
4979      4980    5003  FS-1428586                FED   FS-FIRESTAT   
4980      4981    5004  FS-1428589                FED   FS-FIRESTAT   
4981      4982    5005  FS-1428598                FED   FS-FIRESTAT   
4982      4983    5006  FS-1428599                FED   FS-FIRESTAT   
4983      4984    5007  FS-1428601                FED   FS-FIRESTAT   
4984      4985    5008  FS-1428603                FED   FS-FIRESTAT   
4985      4986    5009  FS-1428610                FED   FS-FIRESTAT   
4986      4987    5010  FS-1428611                FED   FS-FIRESTAT   
4987      4988    5011  FS-1428612                FED   FS-FIRESTAT   
4988      4989    5012  FS-1428613                FED   FS-FIRESTAT   
4989      4990    5013  FS-1428614                FED   FS-FIRESTAT   
4990      4991    5014  FS-1428616                FED   FS-FIRESTAT   
4991      4992    5015  FS-1428617                FED   FS-FIRESTAT   
4992      4993    5016  FS-1428619                FED   FS-FIRESTAT   
4993      4994    5017  FS-1428620                FED   FS-FIRESTAT   
4994      4995    5018  FS-142

In [61]:
# split dataset into train and test lists
filtered_independent = dataset[[
    "STATE", 
    "FIPS_CODE", 
    "LATITUDE", 
    "LONGITUDE", 
    "FIRE_SIZE_CLASS", 
    "FIRE_SIZE", 
    "FIRE_YEAR", 
    "DISCOVERY_DATE",
    "DISCOVERY_TIME",
    "CONT_DATE",
    "CONT_TIME"
]]
filtered_dependent = dataset["STAT_CAUSE_CODE"]
X = filtered_independent.values
y = filtered_dependent.values
filtered_independent.dtypes

STATE               object
FIPS_CODE           object
LATITUDE           float64
LONGITUDE          float64
FIRE_SIZE_CLASS     object
FIRE_SIZE          float64
FIRE_YEAR            int64
DISCOVERY_DATE     float64
DISCOVERY_TIME      object
CONT_DATE          float64
CONT_TIME           object
dtype: object

In [69]:
# using the ColumnTransformer only approach
numerical_features = filtered_independent.dtypes != "object"
categorical_features = ~numerical_features
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

preprocess = make_column_transformer (
    (categorical_features, OneHotEncoder()),
    (categorical_features, defaultMinimumValues),
    (numerical_features, make_pipeline(SimpleImputer(), StandardScaler()))
)
process_columns = filtered_independent.columns == "STATE"
process_columns

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [63]:
createNaiveBayesModel(X_train, y_train, X_test, y_test, preprocess)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/ops.py:792: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)


TypeError: invalid type comparison

In [10]:
createArtificialNeuralNetwork(X_train, y_train, X_test, y_test)


Artificial Neural Network Classifier Section
---------------------------------
Epoch 1/200
3500/3500 [==============================] - 1s 172us/step - loss: 13.7945 - acc: 0.5220
Epoch 2/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 3/200
3500/3500 [==============================] - 0s 21us/step - loss: 13.2523 - acc: 0.5220
Epoch 4/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 5/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 6/200
3500/3500 [==============================] - 0s 21us/step - loss: 13.2523 - acc: 0.5220
Epoch 7/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 8/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 9/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 10/200
3500/3

3500/3500 [==============================] - 0s 23us/step - loss: 13.2523 - acc: 0.5220
Epoch 162/200
3500/3500 [==============================] - 0s 22us/step - loss: 13.2523 - acc: 0.5220
Epoch 163/200
3500/3500 [==============================] - 0s 22us/step - loss: 13.2523 - acc: 0.5220
Epoch 164/200
3500/3500 [==============================] - 0s 21us/step - loss: 13.2523 - acc: 0.5220
Epoch 165/200
3500/3500 [==============================] - 0s 19us/step - loss: 13.2523 - acc: 0.5220
Epoch 166/200
3500/3500 [==============================] - 0s 22us/step - loss: 13.2523 - acc: 0.5220
Epoch 167/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 168/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 169/200
3500/3500 [==============================] - 0s 20us/step - loss: 13.2523 - acc: 0.5220
Epoch 170/200
3500/3500 [==============================] - 0s 21us/step - loss: 13.2523 - acc: 0

/Users/vincentdu/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
creatingRandomForestPredictor(X_train, y_train, X_test, y_test)


Random Forest Classifier Section
---------------------------------
Training set Score:  0.8265714285714286
Testing set Score:  0.6293333333333333
For Random Forest Classification
51.0
[[765   0   0   0   0   0   0   0   0]
 [ 53   0   0   0   0   0   0   0   0]
 [ 25   0   0   0   0   0   0   0   0]
 [253   0   0   0   0   0   0   0   0]
 [ 74   0   0   0   0   0   0   0   0]
 [  6   0   0   0   0   0   0   0   0]
 [124   0   0   0   0   0   0   0   0]
 [ 15   0   0   0   0   0   0   0   0]
 [185   0   0   0   0   0   0   0   0]]
Predicted  True   All
True                 
1.0         765   765
2.0          53    53
3.0          25    25
4.0         253   253
5.0          74    74
6.0           6     6
7.0         124   124
8.0          15    15
9.0         185   185
All        1500  1500
             precision    recall  f1-score   support

        1.0       0.51      1.00      0.68       765
        2.0       0.00      0.00      0.00        53
        3.0       0.00      0.00      0

/Users/vincentdu/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
